language: scala

script: "sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport"

scala:
   - 2.11.11
   - 2.12.3

jdk:
   - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)
 